# Generated by Django 4.0.5 on 2022-06-13 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_tags_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='tags',
            field=models.ManyToManyField(blank=True, to='courses.tags'),
        ),
    ]
