# Generated by Django 4.0.5 on 2022-06-14 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_courses_featured_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='featured_image',
            field=models.ImageField(blank=True, default='def.jpg', null=True, upload_to=''),
        ),
    ]
