# Generated by Django 4.0.5 on 2022-06-14 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_alter_courses_featured_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='link',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
