# Generated by Django 4.0.5 on 2022-06-21 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_courses_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='prof_name',
        ),
    ]
