# Generated by Django 4.0.5 on 2022-06-25 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_profile_profile_image_alter_profile_skill'),
        ('courses', '0008_remove_courses_prof_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courses',
            options={'ordering': ['date_created']},
        ),
        migrations.AddField(
            model_name='comments',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.profile'),
        ),
        migrations.AlterUniqueTogether(
            name='comments',
            unique_together={('owner', 'course')},
        ),
    ]
